apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskmarket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskmarket
  template:
    metadata:
      labels:
        app: flaskmarket
    spec:
      containers:
      - name: flaskmarket
        image: pallavi77/flaskmarket:v1
        ports:
        - containerPort: 5000
